### ISSUE TITLE
Buy new laptop for kids

### ISSUE THREAD

**Issue by recc-tech** [recc-tech/tech#251]
## Absolutely Required

- VGA or HDMI port (to connect to monitor)

## Nice to Have

- USB-A port (to transfer video from MCR video station)
- (If running Windows) At least 8 GB of RAM

## Candidates

- [Dell Latitude E6420, Intel Core i5-2520M](https://www.electro-shop.ca/products/dell-latitude-e6420?variant=43517116317931&F1=4+Go+Ram+%2F+120+Go+SSD&F2=Usag%C3%A9e+fonctionelle&F6=Windows+10+Pro&F3=Fran%C3%A7ais&F4=Garantie+r%C3%A9guli%C3%A8re+-+90+Jours+Pi%C3%A8ces+%26+Main-d%27oeuvre) (external link to electro-shop.ca).
- [Chromebook](https://www.amazon.ca/gp/product/B0BTJF66ZS/ref=ox_sc_act_title_1?smid=A3DWYIK6Y9EEQB&psc=1) and [Dongle](https://www.amazon.ca/gp/product/B07N8RFW86/ref=ox_sc_act_title_3?smid=A2ECQ6PSDL32ED&psc=1)
- Alternatively, the laptop currently used as the prompter device for the stage's confidence monitor could be used as the new kids laptop once that device is liberated by the confidence monitor improvement project.

**Comment by louis-hildebrand** [comment]
We're re-purposing the teleprompter laptop for this.
