### ISSUE TITLE
Repair camera 4

### ISSUE THREAD

**Issue by recc-tech** [recc-tech/tech#288]
The JVC broadcast camera ("camera 4")'s SDI port is broken. In the current signal flow paradigm, this entails that camera 4 is offline, as we rely on the video signal being sent over SDI to the broadcast workstation. 

As a workaround, the camera's HDMI output can be used instead, but the signal must still be converted to SDI prior to entering the broadcast workstation due to the signal transmission constraints of native HDMI.

Therefore, two options: 

1. Send the camera in for evaluation and repair
2. Use existing HDMI to SDI Blackmagic MicroConverter hardware unit to translate from camera HDMI output to SDI

**Comment by Joss98** [comment]
[!] Blocker: Option 2

The available hardware is missing a power supply.

A replacement power supply must be sourced before Option 2 can be pursued.

**Comment by recc-tech** [comment]
Closing issue; JVC camera not repaired, but NDI enabled instead. SDI bypassed via HDMI and then converted to NDI.
