### ISSUE TITLE
Plan Summary has incorrectly-escaped HTML when there's no announcements video

### ISSUE THREAD

**Issue by louis-hildebrand** [recc-tech/tech#365]
On 2024-06-23, there was no announcements video in the plan. If you run `python summarize_plan.py --date 2024-06-23`, the place where the announcement video shows up should say "None found" in red letters. Instead, it says `<span class='Missing'>None found</span>`. I suspect this is due to `html.escape()` being called on this span when it should only be called on "None found".

Check whether the same issue occurs in other cases (e.g., when there's no bumper video).

I think this issue can be addressed at the same time as #339.

![Image](https://github.com/recc-tech/tech/assets/77470815/b9fb0ab9-9e68-4727-8175-27b069d0a1a8)

**Comment by Joss98** [comment]
Addressing at the same time as [](https://github.com/recc-tech/tech/issues/339).
